### ISSUE TITLE
opencv3?

### ISSUE THREAD

**Issue by idefix92** [BestSonny/SSTD#1]
Excuse me, I wanted to ask if I need opencv3 for this repository? I am getting errors which apparently are related to opencv3. I am using only opencv 2.4.9.
And also do I have to use the caffe u ship? I have a caffe version on my ubuntu installation. Is yours modified somehow? 

'make' command generates

~/Desktop/A_M-arbeit/G_Code/G_SSTD$ make -j8
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_videoio

**Comment by BestSonny** [comment]
I guess it is OpenCV library dependency issue. Can you try to run the following command before compiling? 

`sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
sudo apt-get install --no-install-recommends libboost-all-dev`

We made several changes in our caffe version, you have to run code based on it.

**Comment by idefix92** [comment]
@BestSonny Dear Pan, 

I am running some other repositories with shipped caffe. They are compiling without any problem. protobuf and all the other libraries / dependencies are well installed on my ubuntu. However, I will try your command again. Just for information: which open CV are you using?
Best Regards
Valentin

**Comment by BestSonny** [comment]
@idefix92 I run `pkg-config --modversion opencv` and it gives me version `3.2.0`

**Comment by idefix92** [comment]
I supposed so! Thank you very much. I will try to run the fun on a virtual machine :+1:
