### ISSUE TITLE
怎么在没有GPU支持下，使用你们的应用？

### ISSUE THREAD

**Issue by scauhua** [BestSonny/SSTD#10]
在这一步，make test -j8，我们因为没有cuda支持，已经开始编译失败。。。
尝试跳过这步后，尝试编译nms时，也会报错，因为没有nvcc环境，你们有仅支持CPU使用的版本么？

**Comment by BestSonny** [comment]
You can directly skip `make test` phrase.

For NMS compilation, you can refer to the excellent [faster RCNN](https://github.com/rbgirshick/fast-rcnn/blob/master/lib/setup.py) project
