### ISSUE TITLE
when I use only in CPU mode,it come out thie erro，mask_resize_layer.cpp:42] Not Implemented Yet

### ISSUE THREAD

**Issue by scauhua** [BestSonny/SSTD#11]
F1214 12:28:35.162415 154408 mask_resize_layer.cpp:42] Not Implemented Yet，Does it readly need this file?I should write the mask_resize_layer.cpp ?

**Comment by BestSonny** [comment]
Yes. You can refer the GPU implementation

**Comment by SHaiHosh** [comment]
@scauhua 
Have you written the mask_resize_layer.cpp ?
Could you share it if you have?
