### ISSUE TITLE
how to convert data （look like [image, mask, bbox_label]）into lmdb?

### ISSUE THREAD

**Issue by moliqian** [BestSonny/SSTD#12]
#hi,BestSonny. Thanks for your good shared code. when i use the tool "convert_annoset_mask" to convert  database into lmdb, i was OK.   But when i train my net, i get  a problem. It seems the tool "convert_annoset_mask" convert mask(single channel) into 3 channels. I don't knew where i did wrong.
could you tell me why or share your "convert" shell ?
Here is my "convert" command:
## **./build/tools/convert_annoset_mask --anno_type=detection --label_type=xml --label_map_file=/home/shi/caffe-ssd/data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/shi/data/ ### /home/shi/data/all_train.txt /home/shi/data/VOC12_AUG/lmdb/VOC12_train_lmdb** 

# here is the training wrong what showed in Caffe:
### I0105 14:35:56.477653 16084 net.cpp:100] Creating Layer seg_loss
I0105 14:35:56.477654 16084 net.cpp:434] seg_loss <- upscore
I0105 14:35:56.477658 16084 net.cpp:434] seg_loss <- mask
I0105 14:35:56.477661 16084 net.cpp:408] seg_loss -> seg_loss
I0105 14:35:56.477670 16084 layer_factory.hpp:77] Creating layer seg_loss
I0105 14:35:56.485399 16084 softmax_loss_layer.cpp:47] softmaxwithloss bottom[0] size: 2,21,320,320
I0105 14:35:56.485427 16084 softmax_loss_layer.cpp:50] softmaxwithloss bottom[1] size: 2,3,320,320
F0105 14:35:56.485437 16084 softmax_loss_layer.cpp:53] Check failed: outer_num_ * inner_num_ == bottom[1]->count() (204800 vs. 614400) Number of labels must match number of predictions; e.g., if softmax axis == 1 and prediction shape is (N, C, H, W), label count (number of labels) must be N*H*W, with integer values in {0, 1, ..., C-1}.

**Comment by moliqian** [comment]
I have solved the problem. I forget  add  mask_param into annotated_data_mask_layer.

**Comment by chenhao10807** [comment]
@moliqian I have the same problem.Could you please tell me how to solve it?
