### ISSUE TITLE
'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by Omnipresent** [BestSonny/SSTD#16]
I am trying to run `demo_test.py`, however, I'm getting the following error:

`'module' object has no attribute 'LabelMap'`

This error happens on the line: `labelmap = caffe_pb2.LabelMap()`

I have successfully built and installed caffe from master branch https://github.com/BVLC/caffe in `/home/ubuntu/caffe/python` and I can successfully execute `import caffe` and `from caffe.proto import caffe_pb2`

My `PYTHONPATH` is: 

```
ubuntu@ip-10-0-0-14:~/caffe/python$ echo $PYTHONPATH
/home/ubuntu:/home/ubuntu/caffe/python
```

Can someone please let me know what I'm missing?

**Comment by BestSonny** [comment]
@Omnipresent  Please use our customized Caffe for this project.
