### ISSUE TITLE
how to run a demo based on downloaded model?

### ISSUE THREAD

**Issue by Omnipresent** [BestSonny/SSTD#17]
https://github.com/BestSonny/SSTD/issues/9 suggests that the `demo_test.py` file can not be run on a CPU because it takes a long time. It was my understanding that once the model has been built, it can be used to be run on a CPU and still perform fast. 

I'm wondering how would someone put this model in production if even after a built model (`demo.caffemodel`) running the demo on a single image takes a long time?

**Comment by BestSonny** [comment]
@Omnipresent  We didn't implement CPU version of some layers such as mask_resize_layer. Therefore, I think you may fail to run it in CPU model.
