### ISSUE TITLE
Orientation in cuda implementation

### ISSUE THREAD

**Issue by SHaiHosh** [BestSonny/SSTD#18]
SSTD article says: 
"we use a softmax function for binary classification of text or non-text, and apply the smooth-l1 loss for regressing 5 parameters for each word bounding box, including a parameter for box orientation"

I can find the box orientation parameter in the .cpp implementation
But  I cannot find the  box orientation parameter in the .cu implementation

The .cpp implementation (on CPU) cannot run because "mask_resize_layer.cpp:42] Not Implemented Yet"

Is there a way to get orientation from .cu implementation?

Have you already implemented the mask_resize_layer.cpp?

**Comment by BestSonny** [comment]
@SHaiHosh  Did you mean [file1](https://github.com/BestSonny/SSTD/blob/master/src/caffe/layers/detection_oriented_output_layer.cu) and [file2](https://github.com/BestSonny/SSTD/blob/master/src/caffe/layers/multibox_oriented_loss_layer.cpp)?

For the file2, we didn't have a CPU version.

**Comment by SHaiHosh** [comment]
The compilation fails on mask_resize_layer.cpp already - so this is what I meant for

Anyway, is there a way to get the orientation (the box angle) in .cu implementation?
