### ISSUE TITLE
Error with nms? 

### ISSUE THREAD

**Issue by idefix92** [BestSonny/SSTD#2]
I am gettin following error when running dem_test:

File "text/demo_test.py", line 21, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nm

and the contained files in nms are:

cpu_nms.pyx  gpu_nms.pyx  nms_kernel.cu
gpu_nms.hpp  __init__.py  py_cpu_nms.py

I also executed:
sh text/download.sh before starting demo_test.py
Best!

Valentin

**Comment by BestSonny** [comment]
@idefix92 Thank you. Already update in the latest commit.

**Comment by idefix92** [comment]
Sorry for bothering you again but here is the error I am talking about 

root@opencv3:/downloads/SSTD/examples# python text/demo_test.py 
Traceback (most recent call last):
  File "text/demo_test.py", line 21, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
root@opencv3:/downloads/SSTD/examples# python text/demo_test.py 


I am running python text/demo_test.py with python 2.7
