### ISSUE TITLE
Attempt to run CPU only version

### ISSUE THREAD

**Issue by harsh306** [BestSonny/SSTD#22]
`/home/harsh/mlocr/SSTD
['    step: 8', '    step: 16', '    step: 32', '    step: 64', '    step: 78.2222222222', '    step: 100.571428571', '    step: 140.8']
found at line: 3942
found at line: 4363
found at line: 4784
found at line: 5205
found at line: 5626
found at line: 6047
found at line: 6468
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0303 10:59:26.766597 25916 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)
`
Any ideas? I can't figure out why

**Comment by BestSonny** [comment]
@harsh306  Your Caffe is compiled as CPU-only as the error said.
