### ISSUE TITLE
Oriented Text detection

### ISSUE THREAD

**Issue by bado-lee** [BestSonny/SSTD#25]
Hi, Thank you very much for sharing your code.
Currently I'm trying to reproduce result of ICDAR2015 in your paper but I cannot find prototxt for oriented texts (especifically for ICDAR2015 sets).
It would be wonderful if you can share the model and pre-trained model for oriented texts.

**Comment by BestSonny** [comment]
@bado-lee  I am knee deep in working on exams and projects. I am afraid that current I do not have time for maintaining the project. Sorry about this.
