### ISSUE TITLE
Train own model

### ISSUE THREAD

**Issue by covarsha** [BestSonny/SSTD#26]
Could you please give brief instructions regarding how one can train their own model?

**Comment by chenhao10807** [comment]
Could you please give some details about how to train a model?thanks!

**Comment by BestSonny** [comment]
@chenhao10807 @covarsha  I am busy on other research projects and may not have time on maintaining this project.  I also suggest you to check pytorch version [SSTDNet](https://github.com/HotaekHan/SSTDNet) for some details.
