### ISSUE TITLE
i had cudnn version error

### ISSUE THREAD

**Issue by afterimagex** [BestSonny/SSTD#27]
my cuda is 8.0 and cudnn is 5,
but when i compile this code failed.

====
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/blob.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from src/caffe/blob.cpp:4:
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:112:3: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
   CUDNN_CHECK(cudnnSetConvolution2dDescriptor(*conv,
   ^
In file included from ./include/caffe/util/cudnn.hpp:5:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from src/caffe/blob.cpp:4:
/usr/local/cuda/include/cudnn.h:537:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                           ^
Makefile:577: recipe for target '.build_release/src/caffe/blob.o' failed
make: *** [.build_release/src/caffe/blob.o] Error 1

====

please told me your cudnn and cuda version

**Comment by BestSonny** [comment]
@afterimagex Try to use a cuda 7.5 to see whether it solves the problem.

**Comment by rlazkani** [comment]
I faced the same problem using cuda 10 and cudnn 7.5.

**Comment by yeduzhouzi** [comment]
> I faced the same problem using cuda 10 and cudnn 7.5.

Did you solve the problem? Some say that cudnn of lower version should be used, but it's bound to the version of cuda, which is further bound to the version of Matlab. It's just impossible to lower all their versions.

**Comment by NidhiSultan** [comment]
@afterimagex, how did you configure the caffee in the system? I am trying to run the demo but getting errors like Labelmap not present or from nms folder.
New to c++, please help in solving this query.

Thanks in advance
Nidhi
