### ISSUE TITLE
cpu running

### ISSUE THREAD

**Issue by idefix92** [BestSonny/SSTD#5]
As your Algorithm requires Opencv 3+ I had to create a VM as I don't want it to interfere with my 2.4 on the regular operating system. However, the capacity of my GPU is not enough to run a GPU calculation within the VM (or the passthrough does not work properly) therefore I wanted to ask if there is an opportunity to run the code on my images, only on CPU? 

BR
Valentin

**Comment by BestSonny** [comment]
I think you can run it with CPU, but very slowly.
