### ISSUE TITLE
可以在windows上运行吗？

### ISSUE THREAD

**Issue by xrf116** [BestSonny/SSTD#6]
你这里的caffe有修改过什么吗？可以用官方的caffe替代么？因为官方支持windows下编译

**Comment by BestSonny** [comment]
@xrf116 有改动， [1](https://github.com/BestSonny/SSTD/blob/master/src/caffe/layers/annotated_data_mask_layer.cpp),[2](https://github.com/BestSonny/SSTD/blob/master/src/caffe/layers/annotated_data_mask_layer.cu),
 mask_pooling, mask_resize, prior_box_layer 
不能支持windows。
