### ISSUE TITLE
do not have   text/download.sh

### ISSUE THREAD

**Issue by 10183308** [BestSonny/SSTD#8]
1. do not have text/download.sh

2. do not have /examples/text/model/final_deploy.prototxt

**Comment by BestSonny** [comment]
@10183308  Thank you very much.

Sorry about the wrong README, you can directly download the model via [google drive](https://docs.google.com/uc?export=download&id=0Bx8FPKhlXE1lOTF1TzIxOGhsblk)
 or [baiduyun](https://pan.baidu.com/s/1c1ML6dM)

The final_deploy.prototxt will be generated automatically, once you run 

`python text/demo_test.py`

The motivation to use final_deploy.prototxt is to adjust the step sizes (should be size of image / size of feature map)
