### ISSUE TITLE
when I run python text/demp_test.py,a error occured

### ISSUE THREAD

**Issue by kmustriver** [BestSonny/SSTD#9]
warn("The default mode, 'constant', will be changed to 'reflect' in "
F1206 10:15:04.766489   447 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)
How should I do for this?

**Comment by BestSonny** [comment]
@kmustriver out of memory. Your GPU capacity is not large enough.

**Comment by kmustriver** [comment]
my GPU is 1050TI,have 4GB memory,can't run this demo?

**Comment by BestSonny** [comment]
@kmustriver  I think so. Maybe you can reduce the image size.
